# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require "yaml"

fastlane_version "1.102.0"

default_platform :android

CONF = YAML.load_file('conf.yml')

platform :android do

  before_all do
  ENV["SLACK_URL"] = CONF["slack"]["webhookurl"]
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Upload to DeployGate"
  lane :inhouse do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    deploygate(
      api_token: '47221ab085a9681c410176e2c0d8e4c8aa1b9f63', # もしくは環境変数 DEPLOYGATE_API_TOKEN にて設定可能
      user: 'taross', # もしくは環境変数 DEPLOYGATE_USER にて設定可能
      apk: apk_path,
      message: "Fastlane build #{lane_context[SharedValues::BUILD_NUMBER]}",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  after_all do |lane|
    slack(message: "Successfully")
  end

  error do |lane, exception|
  slack(
    message: exception.message,
    success: false
  )
  end
end
